// utils/constants.js
export const STATUS_OPTIONS = [
  { value: 'all', label: 'All Statuses' },
  { value: 'new', label: 'New' },
  { value: 'reviewed', label: 'Reviewed' },
  { value: 'interview', label: 'Interview' },
  { value: 'offer', label: 'Offer' },
  { value: 'hired', label: 'Hired' },
  { value: 'rejected', label: 'Rejected' }
];

export const ROLE_OPTIONS = [
  { value: 'all', label: 'All Roles' },
  { value: 'frontend', label: 'Frontend Developer' },
  { value: 'backend', label: 'Backend Developer' },
  { value: 'fullstack', label: 'Full Stack Developer' },
  { value: 'designer', label: 'UI/UX Designer' },
  { value: 'pm', label: 'Product Manager' }
];

export const DATE_OPTIONS = [
  { value: 'all', label: 'All Time' },
  { value: 'today', label: 'Today' },
  { value: 'week', label: 'This Week' },
  { value: 'month', label: 'This Month' },
  { value: 'custom', label: 'Custom Range' }
];

export const JOB_ROLES = [
  'Software Engineer',
  'Senior Software Engineer',
  'Lead Software Engineer',
  'Principal Software Engineer',
  'Staff Software Engineer',
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'Mobile App Developer',
  'iOS Developer',
  'Android Developer',
  'React Developer',
  'Angular Developer',
  'Vue.js Developer',
  'Node.js Developer',
  'Python Developer',
  'Java Developer',
  '.NET Developer',
  'PHP Developer',
  'Ruby Developer',
  'Go Developer',
  'Rust Developer',
  'C++ Developer',
  'Embedded Systems Engineer',
  'Firmware Engineer',
  'Hardware Engineer',
  'FPGA Engineer',
  'ASIC Design Engineer',
  'DevOps Engineer',
  'Site Reliability Engineer (SRE)',
  'Cloud Architect',
  'AWS Solutions Architect',
  'Azure Solutions Architect',
  'GCP Solutions Architect',
  'Infrastructure Engineer',
  'Platform Engineer',
  'Release Engineer',
  'Build Engineer',
  'Systems Administrator',
  'Network Engineer',
  'Security Engineer',
  'Cybersecurity Analyst',
  'Penetration Tester',
  'Security Architect',
  'Data Scientist',
  'Senior Data Scientist',
  'Principal Data Scientist',
  'Data Engineer',
  'Data Analyst',
  'Business Intelligence Analyst',
  'Machine Learning Engineer',
  'AI Engineer',
  'Deep Learning Engineer',
  'MLOps Engineer',
  'Computer Vision Engineer',
  'NLP Engineer',
  'Research Scientist',
  'Quantitative Analyst',
  'Database Administrator',
  'Big Data Engineer',
  'Product Manager',
  'Senior Product Manager',
  'Principal Product Manager',
  'Product Owner',
  'Technical Product Manager',
  'Growth Product Manager',
  'UX Designer',
  'UI Designer',
  'UX/UI Designer',
  'Product Designer',
  'Interaction Designer',
  'Visual Designer',
  'Graphic Designer',
  'Motion Designer',
  'Design Systems Designer',
  'User Researcher',
  'UX Researcher',
  'Engineering Manager',
  'Senior Engineering Manager',
  'Director of Engineering',
  'VP of Engineering',
  'CTO',
  'Technical Lead',
  'Team Lead',
  'Scrum Master',
  'Agile Coach',
  'Project Manager',
  'Technical Project Manager',
  'Program Manager',
  'QA Engineer',
  'Test Engineer',
  'Automation Test Engineer',
  'Performance Test Engineer',
  'QA Lead',
  'Test Manager',
  'Sales Engineer',
  'Solutions Engineer',
  'Technical Sales Representative',
  'Customer Success Manager',
  'Technical Account Manager',
  'Marketing Manager',
  'Digital Marketing Manager',
  'Growth Marketing Manager',
  'Content Marketing Manager',
  'SEO Specialist',
  'SEM Specialist',
  'Technical Support Engineer',
  'Customer Support Engineer',
  'Solutions Consultant',
  'Implementation Consultant',
  'Technical Consultant',
  'Business Analyst',
  'Systems Analyst',
  'IT Specialist',
  'Help Desk Technician',
  'Financial Analyst',
  'Business Development Manager',
  'Legal Counsel',
  'Compliance Officer',
  'Risk Analyst',
  'HR Manager',
  'Talent Acquisition Specialist',
  'Recruiter',
  'Technical Recruiter',
  'HR Business Partner',
  'Blockchain Developer',
  'Smart Contract Developer',
  'Game Developer',
  'Unity Developer',
  'Unreal Engine Developer',
  'AR/VR Developer',
  'IoT Engineer',
  'Robotics Engineer',
  'Biomedical Engineer',
  'Aerospace Engineer',
  'Mechanical Engineer',
  'Electrical Engineer',
  'Chemical Engineer',
  'Civil Engineer'
];