export const mockCandidates = [
  {
    Resume_ID: "RES-1001",
    FirstName: "John",
    LastName: "Doe",
    EmailID: "john.doe@example.com",
    CountryCode: "+1",
    PhoneNumber1: "5551234567",
    PhoneNumber2: "5559876543",
    ResumeUpload: {
      name: "John_Doe_Resume.pdf",
      size: 245760, // 240KB
      type: "application/pdf",
      lastModified: 1634567890000
    },
    CandidateInfo: "Senior Full Stack Developer with 8+ years experience in JavaScript frameworks",
    CurrentLocation: "New York, NY",
    CurrentSalary: "$120,000",
    ExpectedSalary: "$140,000",
    NoticePeriod: "1 month",
    CurrentEmployer: "Tech Innovations Inc.",
    Experience: "8",
    JobRoleApplied: "Senior Software Engineer",
    Dob: "1985-06-15",
    LinkedInProfile: "linkedin.com/in/johndoe",
    CoverLetter: "I'm excited about the opportunity to work with cutting-edge technologies...",
    PassportNo: "AB1234567",
    Status: "Interview",
    CreatedDt: "2023-05-15T10:30:00Z",
    CreatedBy: "Admin",
    UpdatedDt: "2023-05-20T14:15:00Z",
    UpdatedBy: "HR_Team",
    Skills: ["JavaScript", "React", "Node.js", "TypeScript", "AWS", "Docker", "GraphQL"],
    Education: "MS in Computer Science, MIT",
    Certifications: ["AWS Certified Developer", "Google Cloud Professional"]
  },
  {
    Resume_ID: "RES-1002",
    FirstName: "Sarah",
    LastName: "Johnson",
    EmailID: "sarah.j@example.com",
    CountryCode: "+44",
    PhoneNumber1: "2071234567",
    ResumeUpload: {
      name: "Sarah_Johnson_CV.docx",
      size: 102400, // 100KB
      type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      lastModified: 1634200000000
    },
    CandidateInfo: "UX/UI Designer with strong portfolio in enterprise applications",
    CurrentLocation: "London, UK",
    CurrentSalary: "£65,000",
    ExpectedSalary: "£75,000",
    NoticePeriod: "2 weeks",
    CurrentEmployer: "DesignHub Ltd",
    Experience: "5",
    JobRoleApplied: "Lead UX Designer",
    Dob: "1990-11-22",
    LinkedInProfile: "linkedin.com/in/sarahjdesign",
    Status: "Reviewed",
    CreatedDt: "2023-06-10T09:15:00Z",
    CreatedBy: "Recruiter_1",
    Skills: ["Figma", "Sketch", "Adobe XD", "User Research", "Prototyping", "HTML/CSS"],
    Education: "BFA in Design, Royal College of Art",
    Certifications: ["NN/g UX Certification"]
  },
  {
    Resume_ID: "RES-1003",
    FirstName: "Michael",
    LastName: "Chen",
    EmailID: "michael.chen@example.com",
    CountryCode: "+86",
    PhoneNumber1: "13800138000",
    ResumeUpload: {
      name: "Michael_Chen_Resume.pdf",
      size: 307200, // 300KB
      type: "application/pdf",
      lastModified: 1635000000000
    },
    CandidateInfo: "Data Scientist specializing in machine learning and big data analytics",
    CurrentLocation: "Shanghai, China",
    CurrentSalary: "¥800,000",
    ExpectedSalary: "¥1,000,000",
    NoticePeriod: "3 months",
    CurrentEmployer: "DataTech Solutions",
    Experience: "6",
    JobRoleApplied: "Senior Data Scientist",
    Dob: "1988-03-08",
    LinkedInProfile: "linkedin.com/in/michaelchen-ds",
    Status: "New",
    CreatedDt: "2023-07-05T14:30:00Z",
    CreatedBy: "System",
    Skills: ["Python", "TensorFlow", "PyTorch", "SQL", "Big Data", "Data Visualization", "Spark"],
    Education: "PhD in Computer Science, Tsinghua University",
    Certifications: ["Google Professional Data Engineer", "AWS Certified Data Analytics"]
  },
  {
    Resume_ID: "RES-1004",
    FirstName: "Priya",
    LastName: "Patel",
    EmailID: "priya.patel@example.com",
    CountryCode: "+91",
    PhoneNumber1: "9876543210",
    PhoneNumber2: "9876543211",
    ResumeUpload: {
      name: "Priya_Patel_Resume.pdf",
      size: 204800, // 200KB
      type: "application/pdf",
      lastModified: 1634500000000
    },
    CandidateInfo: "DevOps Engineer with AWS and Kubernetes expertise",
    CurrentLocation: "Bangalore, India",
    CurrentSalary: "₹1,800,000",
    ExpectedSalary: "₹2,200,000",
    NoticePeriod: "1 month",
    CurrentEmployer: "CloudTech Services",
    Experience: "4",
    JobRoleApplied: "DevOps Specialist",
    Dob: "1992-09-17",
    LinkedInProfile: "linkedin.com/in/priyapatel-devops",
    Status: "Offer",
    CreatedDt: "2023-06-28T11:45:00Z",
    CreatedBy: "Recruiter_2",
    Skills: ["AWS", "Kubernetes", "Terraform", "CI/CD", "Docker", "Jenkins", "Linux"],
    Education: "BE in Computer Engineering, IIT Bombay",
    Certifications: ["AWS Certified DevOps Engineer", "Certified Kubernetes Administrator"]
  },
  {
    Resume_ID: "RES-1005",
    FirstName: "David",
    LastName: "Wilson",
    EmailID: "david.wilson@example.com",
    CountryCode: "+1",
    PhoneNumber1: "4151234567",
    ResumeUpload: null, // No resume uploaded
    CandidateInfo: "Product Manager with fintech experience",
    CurrentLocation: "San Francisco, CA",
    CurrentSalary: "$135,000",
    ExpectedSalary: "$150,000",
    NoticePeriod: "1 month",
    CurrentEmployer: "FinTech Solutions",
    Experience: "7",
    JobRoleApplied: "Senior Product Manager",
    Dob: "1987-12-03",
    LinkedInProfile: "linkedin.com/in/davidwilson-pm",
    Status: "Rejected",
    CreatedDt: "2023-07-12T16:20:00Z",
    CreatedBy: "HR_Team",
    Skills: ["Product Strategy", "Roadmapping", "Agile", "User Stories", "Market Research", "JIRA", "SQL"],
    Education: "MBA, Stanford University",
    Certifications: ["Pragmatic Marketing Certified", "SAFe Product Owner"]
  },
  {
    Resume_ID: "RES-1006",
    FirstName: "Emma",
    LastName: "Garcia",
    EmailID: "emma.g@example.com",
    CountryCode: "+34",
    PhoneNumber1: "912345678",
    ResumeUpload: {
      name: "Emma_Garcia_CV.pdf",
      size: 184320, // 180KB
      type: "application/pdf",
      lastModified: 1634800000000
    },
    CandidateInfo: "Frontend Developer with React and TypeScript expertise",
    CurrentLocation: "Madrid, Spain",
    CurrentSalary: "€45,000",
    ExpectedSalary: "€55,000",
    NoticePeriod: "2 weeks",
    CurrentEmployer: "WebCraft Studios",
    Experience: "3",
    JobRoleApplied: "Frontend Developer",
    Dob: "1993-07-25",
    LinkedInProfile: "linkedin.com/in/emmagarcia-dev",
    Status: "Hired",
    CreatedDt: "2023-06-15T13:10:00Z",
    CreatedBy: "Recruiter_1",
    Skills: ["React", "TypeScript", "Redux", "CSS/SASS", "Jest", "GraphQL", "Next.js"],
    Education: "BS in Computer Science, Universidad Politécnica de Madrid",
    Certifications: ["React Certification", "Frontend Masters Certificate"]
  },
  {
    Resume_ID: "RES-1007",
    FirstName: "Praveen",
    LastName: "Kumar",
    EmailID: "mvpraveenkumar24@gmail.com",
    CountryCode: "+91",
    PhoneNumber1: "0558694006",
    ResumeUpload: {
      name: "Praveen_Kumar_Resume.pdf",
      size: 225280, // 220KB
      type: "application/pdf",
      lastModified: 1634900000000
    },
    CandidateInfo: "Backend Developer with expertise in Java and Spring Boot",
    CurrentLocation: "Mannargudi",
    CurrentSalary: "$90,000",
    ExpectedSalary: "$110,000",
    NoticePeriod: "1 month",
    CurrentEmployer: "Tech Corp",
    Experience: "5",
    JobRoleApplied: "Backend Developer",
    Dob: "1991-04-12",
    LinkedInProfile: "linkedin.com/in/praveenkumar-dev",
    Status: "New",
    CreatedDt: "2023-07-25T09:00:00Z",
    CreatedBy: "Current User",
    Skills: ["Java", "Spring Boot", "Microservices", "REST APIs", "SQL", "Docker", "Kafka"],
    Education: "BTech in Computer Science, Anna University",
    Certifications: ["Oracle Certified Professional", "Spring Professional"]
  }
];