// export const allFields = [
//     "firstName",
//     "lastName",
//     "email",
//     "phone",
//     "mobile",
//     "website",
//     "secondaryEmail",
//     "fax",
//     "street",
//     "city",
//     "country",
//     "postalCode",
//     "province",
//     "experience",
//     "currentJobTitle",
//     "expectedSalary",
//     "skillSet",
//     "skypeID",
//     "highestQualification",
//     "currentEmployer",
//     "currentSalary",
//     "additionalInfo",
//     "linkedIn",
//     "twitter",
//     "facebook",
//     "education",
//     "workexperience",
//   ];
  
//   export const candidateFilterFieldMapping = {
//     "First Name": "firstName",
//     "Last Name": "lastName",
//     "Email": "email",
//     "Phone": "phone",
//     "Mobile": "mobile",
//     "Website": "website",
//     "Secondary Email": "secondaryEmail",
//     "Fax": "fax",
//     "Street": "street",
//     "City": "city",
//     "Country": "country",
//     "Postal Code": "postalCode",
//     "Province": "province",
//     "Experience": "experience",
//     "Current Job Title": "currentJobTitle",
//     "Expected Salary": "expectedSalary",
//     "Skill Set": "skillSet",
//     "Skype ID": "skypeID",
//     "Highest Qualification": "highestQualification",
//     "Current Employer": "currentEmployer",
//     "Current Salary": "currentSalary",
//     "Additional Info": "additionalInfo",
//     "LinkedIn": "linkedIn",
//     "Twitter": "twitter",
//     "Facebook": "facebook",
   
//   };
  
//   export const filters = {
//     "First Name": ["is", "isn't", "contains"],
//     "Last Name": ["is", "isn't", "contains"],
//     "Email": ["is", "isn't", "contains"],
//     "Phone": ["is", "isn't", "contains"],
//     "Mobile": ["is", "isn't", "contains"],
//     "Website": ["contains", "doesn't contain"],
//     "Secondary Email": ["contains", "doesn't contain"],
//     "Fax": ["is", "isn't", "contains"],
//     "City": ["is", "isn't", "contains"],
//     "Country": ["is", "isn't", "contains"],
//     "Postal Code": ["is", "isn't", "contains"],
//     "Province": ["is", "isn't", "contains"],
//     "Experience": ["is", "greater than", "less than"],
//     "Current Job Title": ["is", "isn't", "contains"],
//     "Expected Salary": ["greater than", "less than", "is"],
//     "Skill Set": ["contains", "doesn't contain"],
//     "Skype ID": ["is", "isn't"],
//     "Highest Qualification": ["is", "isn't", "contains"],
//     "Current Employer": ["is", "isn't", "contains"],
//     "Current Salary": ["greater than", "less than", "is"],
//     "Additional Info": ["contains", "doesn't contain"],
//     "LinkedIn": ["contains", "doesn't contain"],
//     "Twitter": ["contains", "doesn't contain"],
//     "Facebook": ["contains", "doesn't contain"],
//   };
  
//   export const availableColumns = [
//     { key: "firstName", label: "First Name" },
//     { key: "lastName", label: "Last Name" },
//     { key: "email", label: "Email" },
//     { key: "phone", label: "Phone" },
//     { key: "mobile", label: "Mobile" },
//     { key: "website", label: "Website" },
//     { key: "secondaryEmail", label: "Secondary Email" },
//     { key: "fax", label: "Fax" },
//     { key: "street", label: "Street" },
//     { key: "city", label: "City" },
//     { key: "country", label: "Country" },
//     { key: "postalCode", label: "Postal Code" },
//     { key: "province", label: "Province" },
//     { key: "experience", label: "Experience" },
//     { key: "currentJobTitle", label: "Current Job Title" },
//     { key: "expectedSalary", label: "Expected Salary" },
//     { key: "skillSet", label: "Skill Set" },
//     { key: "skypeID", label: "Skype ID" },
//     { key: "highestQualification", label: "Highest Qualification" },
//     { key: "currentEmployer", label: "Current Employer" },
//     { key: "currentSalary", label: "Current Salary" },
//     { key: "additionalInfo", label: "Additional Info" },
//     { key: "linkedIn", label: "LinkedIn" },
//     { key: "twitter", label: "Twitter" },
//     { key: "facebook", label: "Facebook" },
    
//   ];
  