
// export const allFields = [
//     "clientId",
//     "clientName",
//     "industry",
//     "parentClientId",
//     "website",
//     "createdAt",
//     "contactNumber",
//     "accountManager",
//     "fax",
//     "billingStreet",
//     "billingCity",
//     "billingProvince",
//     "billingPostalCode",
//     "billingCountry",
//     "shippingStreet",
//     "shippingCity",
//     "shippingProvince",
//     "shippingPostalCode",
//     "shippingCountry"
//   ];
// export const clientFilterFieldMapping = {
//     "Client ID": "clientId",
//     "Client Name": "clientName",
//     "Industry": "industry",
//     "Parent Client ID": "parentClientId",
//     "Website": "website",
//     "Created At": "createdAt",
//     "Contact Number": "contactNumber",
//     "Account Manager": "accountManager",
//     "Fax": "fax",
//     "Billing Street": "billingStreet",
//     "Billing City": "billingCity",
//     "Billing Province": "billingProvince",
//     "Billing Postal Code": "billingPostalCode",
//     "Billing Country": "billingCountry",
//     "Shipping Street": "shippingStreet",
//     "Shipping City": "shippingCity",
//     "Shipping Province": "shippingProvince",
//     "Shipping Postal Code": "shippingPostalCode",
//     "Shipping Country": "shippingCountry",
//   };
  
//   export const filters = {
//     "Client ID": ["is", "isn't", "contains"],
//     "Client Name": ["is", "isn't", "contains"],
//     "Industry": ["is", "isn't", "contains"],
//     "Parent Client ID": ["is", "isn't"],
//     "Website": ["contains", "doesn't contain"],
//     "Created At": ["Today", "Yesterday", "This week", "This Month", "This Year"],
//     "Contact Number": ["is", "isn't", "contains"],
//     "Account Manager": ["is", "isn't", "Current User"],
//     "Fax": ["is", "isn't", "contains"],
//     "Billing City": ["is", "isn't", "contains"],
//     "Billing Province": ["is", "isn't", "contains"],
//     "Billing Postal Code": ["is", "isn't", "contains"],
//     "Billing Country": ["is", "isn't", "contains"],
//     "Shipping City": ["is", "isn't", "contains"],
//     "Shipping Province": ["is", "isn't", "contains"],
//     "Shipping Postal Code": ["is", "isn't", "contains"],
//     "Shipping Country": ["is", "isn't", "contains"],
//   };
  
//   export const availableColumns = [
//     { key: "clientId", label: "Client ID" },
//     { key: "clientName", label: "Client Name" },
//     { key: "industry", label: "Industry" },
//     { key: "parentClientId", label: "Parent Client ID" },
//     { key: "website", label: "Website" },
//     { key: "createdAt", label: "Created At" },
//     { key: "contactNumber", label: "Contact Number" },
//     { key: "accountManager", label: "Account Manager" },
//     { key: "fax", label: "Fax" },
//     { key: "billingStreet", label: "Billing Street" },
//     { key: "billingCity", label: "Billing City" },
//     { key: "billingProvince", label: "Billing Province" },
//     { key: "billingPostalCode", label: "Billing Postal Code" },
//     { key: "billingCountry", label: "Billing Country" },
//     { key: "shippingStreet", label: "Shipping Street" },
//     { key: "shippingCity", label: "Shipping City" },
//     { key: "shippingProvince", label: "Shipping Province" },
//     { key: "shippingPostalCode", label: "Shipping Postal Code" },
//     { key: "shippingCountry", label: "Shipping Country" },
//   ];
  
  