// export const allFields = [
//     "firstName",
//     "lastName",
//     "department",
//     "fax",
//     "clientName",
//     "email",
//     "secondaryEmail",
//     "jobTitle",
//     "workPhone",
//     "mobile",
//     "mailingStreet",
//     "mailingCity",
//     "mailingProvince",
//     "mailingPostalCode",
//     "mailingCountry",
//     "otherStreet",
//     "otherCity",
//     "otherProvince",
//     "otherPostalCode",
//     "otherCountry",
//     "linkedin",
//     "facebook",
//     "twitter",
//     "source",
//     "contactOwner",
//     "isPrimaryContact",
//     "emailOptOut",
//     "description"
//   ];
//   export const contactFilterFieldMapping = {
//     "First Name": "firstName",
//     "Last Name": "lastName",
//     "Department": "department",
//     "Fax": "fax",
//     "Client Name": "clientName",
//     "Email": "email",
//     "Secondary Email": "secondaryEmail",
//     "Job Title": "jobTitle",
//     "Work Phone": "workPhone",
//     "Mobile": "mobile",
//     "Mailing Street": "mailingStreet",
//     "Mailing City": "mailingCity",
//     "Mailing Province": "mailingProvince",
//     "Mailing Postal Code": "mailingPostalCode",
//     "Mailing Country": "mailingCountry",
//     "Other Street": "otherStreet",
//     "Other City": "otherCity",
//     "Other Province": "otherProvince",
//     "Other Postal Code": "otherPostalCode",
//     "Other Country": "otherCountry",
//     "LinkedIn": "linkedin",
//     "Facebook": "facebook",
//     "Twitter": "twitter",
//     "Source": "source",
//     "Contact Owner": "contactOwner",
//     "Is Primary Contact": "isPrimaryContact",
//     "Email Opt Out": "emailOptOut",
//     "Description": "description"
//   };
//   export const filters = {
//     "First Name": ["is", "isn't", "contains"],
//     "Last Name": ["is", "isn't", "contains"],
//     "Department": ["is", "isn't", "contains"],
//     "Fax": ["is", "isn't", "contains"],
//     "Client Name": ["is", "isn't", "contains"],
//     "Email": ["contains", "doesn't contain"],
//     "Secondary Email": ["contains", "doesn't contain"],
//     "Job Title": ["is", "isn't", "contains"],
//     "Work Phone": ["is", "isn't", "contains"],
//     "Mobile": ["is", "isn't", "contains"],
//     "Mailing City": ["is", "isn't", "contains"],
//     "Mailing Province": ["is", "isn't", "contains"],
//     "Mailing Postal Code": ["is", "isn't", "contains"],
//     "Mailing Country": ["is", "isn't", "contains"],
//     "Other City": ["is", "isn't", "contains"],
//     "Other Province": ["is", "isn't", "contains"],
//     "Other Postal Code": ["is", "isn't", "contains"],
//     "Other Country": ["is", "isn't", "contains"],
//     "LinkedIn": ["contains", "doesn't contain"],
//     "Facebook": ["contains", "doesn't contain"],
//     "Twitter": ["contains", "doesn't contain"],
//     "Source": ["is", "isn't", "contains"],
//     "Contact Owner": ["is", "isn't", "Current User"],
//     "Is Primary Contact": ["is", "isn't"],
//     "Email Opt Out": ["is", "isn't"],
//     "Description": ["contains", "doesn't contain"]
//   };
//   export const availableColumns = [
//     { key: "firstName", label: "First Name" },
//     { key: "lastName", label: "Last Name" },
//     { key: "department", label: "Department" },
//     { key: "fax", label: "Fax" },
//     { key: "clientName", label: "Client Name" },
//     { key: "email", label: "Email" },
//     { key: "secondaryEmail", label: "Secondary Email" },
//     { key: "jobTitle", label: "Job Title" },
//     { key: "workPhone", label: "Work Phone" },
//     { key: "mobile", label: "Mobile" },
//     { key: "mailingStreet", label: "Mailing Street" },
//     { key: "mailingCity", label: "Mailing City" },
//     { key: "mailingProvince", label: "Mailing Province" },
//     { key: "mailingPostalCode", label: "Mailing Postal Code" },
//     { key: "mailingCountry", label: "Mailing Country" },
//     { key: "otherStreet", label: "Other Street" },
//     { key: "otherCity", label: "Other City" },
//     { key: "otherProvince", label: "Other Province" },
//     { key: "otherPostalCode", label: "Other Postal Code" },
//     { key: "otherCountry", label: "Other Country" },
//     { key: "linkedin", label: "LinkedIn" },
//     { key: "facebook", label: "Facebook" },
//     { key: "twitter", label: "Twitter" },
//     { key: "source", label: "Source" },
//     { key: "contactOwner", label: "Contact Owner" },
//     { key: "isPrimaryContact", label: "Is Primary Contact" },
//     { key: "emailOptOut", label: "Email Opt Out" },
//     { key: "description", label: "Description" }
//   ];
  